FROM node:16-alpine

LABEL maintainer="Leonardo Pliskieviski <leonardopliski@gmail.com>"

RUN mkdir -p /usr/src/app

WORKDIR /usr/src/app

COPY package.json package-lock.json ./
RUN npm i --legacy-peer-deps

COPY . .

EXPOSE 3000
